service: cloudfront-s3-sandbox
frameworkVersion: '3'

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ${self:service}-${sls:stage}
      localDir: public

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  memorySize: 128
  architecture: arm64

functions:
  function1:
    handler: index.handler

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}
